<?php
include_once 'templates/header.phtml';
?>
<!-- formulario de alta de serie -->
<div class="container">
    <h3>Editar serie <?php echo $serie->titulo ?> </h3>
</div>
<div class="container">
    <form action=<?php echo "series/edit/$serie->id_serie" ?> method="POST" class="my-4">
        <div class="row">
            <div class="col-9">
                <div class="form-group">
                    <label>Título</label>
                    <input required name="titulo" type="text" class="form-control" value=<?php echo "$serie->titulo" ?>>
                </div>
            </div>

            <div class="col-3">
                <div class="form-group">
                    <label>Género</label>
                    <select required name="genero" class="form-control">
                        <option value="Acción" <?php if ($serie->genero == "Acción") echo "selected" ?>>Acción</option>
                        <option value="Terror" <?php if ($serie->genero == "Terror") echo "selected" ?>>Terror</option>
                        <option value="Comedia" <?php if ($serie->genero == "Comedia") echo "selected" ?>>Comedia</option>
                        <option value="Suspenso" <?php if ($serie->genero == "Suspenso") echo "selected" ?>>Suspenso</option>
                        <option value="Animada" <?php if ($serie->genero == "Animada") echo "selected" ?>>Animada</option>
                    </select>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary mt-2">Guardar</button>
    </form>
</div>