<?php
include_once 'templates/header.phtml';
?>
<div class="container mt-5">
    <h3 class="text-center">Editar capítulo <?php echo $capitulo->nombre ?></h3>
</div>
<!-- formulario de alta de serie -->
<div class="container">

    <form action=<?php echo "capitulos/edit/$capitulo->id_capitulo" ?> method="POST" class="my-4">
        <div class="form-group">
            <label>Nombre</label>
            <input required name="nombre" type="text" class="form-control" value=<?php echo "$capitulo->nombre" ?>>
        </div>
        <div class="form-group">
            <label>Duracion</label>
            <input type=number name="duracion" class="form-control" value=<?php echo "$capitulo->duracion" ?>>
        </div>

        <button type="submit" class="btn btn-primary mt-2">Guardar</button>
    </form>
</div>