<?php
include_once 'templates/header.phtml';


echo "<table class=table>
<thead>
  <tr>
  <th scope=>id_serie</th>
  <th scope=>título</th>
  <th scope=>género</th>
  <th scope=>director</th>
  </tr>
  </thead>
  <tbody>";

foreach ($series as $serie) {
    echo "
    <tr>
      <th scope=>$serie->id_serie</th>
      <td>$serie->título</td>
      <td>$serie->género</td>
      <td>$serie->director</td>
    </tr>";
}

echo "</table>";
