<?php require_once 'templates/header.phtml' ?>

<div class="container mt-3">
  <div class="row justify-content-between">
    <div class="col-8">
      <h3>Series</h3>
    </div>
    <!-- Solamente mostrar esto si el usuario esta logueado-->

    <div class="col-3">
      <?php
      if ($isLogged) { ?>
        <a href="series/agregar/" type="button" class='btn btn-primary ml-auto'>Nueva serie</a>
      <?php } ?>
    </div>
  </div>
</div>
<div class="container mt-3">

  <table class=table>
    <thead>
      <tr>
        <th scope=>id_serie</th>
        <th scope=>titulo</th>
        <th scope=>genero</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>

      <?php foreach ($series as $serie) { ?>

        <tr class="item item-serie">
          <th scope=><?= $serie->id_serie ?></th>
          <td><?= $serie->titulo ?></td>
          <td><?= $serie->genero ?></td>

          <td><a <?php echo "href=series/capitulos/$serie->id_serie" ?> class="link-primary">Ver capítulos</a></td>

          <?php
          if ($isLogged) { ?>
            <td><a href="series/editar/<?php echo $serie->id_serie ?>" type="button" class='btn btn-success ml-auto'>Editar</a></td>
            <td><a href="series/eliminar/<?php echo $serie->id_serie ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a></td>
          <?php } ?>
        </tr>
      <?php } ?>

    </tbody>

  </table>
</div>

<?php include_once 'templates/footer.phtml' ?>