<?php
include_once 'templates/header.phtml';
?>
<div class="container mt-5">
    <h3 class="text-center">Agregar capítulo</h3>
</div>

<div class="container">

    <form action="capitulos/add" method="POST" class="my-4">
        <div class="form-group">
            <label>Nombre</label>
            <input required name="nombre" type="text" class="form-control">
        </div>
        <div class="form-group">
            <label>Duracion</label>
            <input type=number name="duracion" class="form-control">
        </div>
        <div class="form-group">
            <label>Serie</label>
            <select class="form-select" name="id_serie">
                <?php foreach ($series as $serie) { ?>
                    <option value=<?php echo "$serie->id_serie" ?>><?php echo $serie->titulo ?></option>
                <?php } ?>
            </select>
        </div>
        <button type="submit" class="btn btn-primary mt-2">Guardar</button>
    </form>
</div>