<?php
include_once 'templates/header.phtml';
?>
<!-- formulario de alta de serie -->
<div class="container">
    <h3>Agregar serie</h3>
</div>
<div class="container">
    <form action="series/add" method="POST" class="my-4">
        <div class="row">
            <div class="col-9">
                <div class="form-group">
                    <label>Título</label>
                    <input required name="titulo" type="text" class="form-control">
                </div>
            </div>

            <div class="col-3">
                <div class="form-group">
                    <label>Género</label>
                    <select required name="genero" class="form-control">
                        <option value="Acción">Acción</option>
                        <option value="Terror">Terror</option>
                        <option value="Comedia">Comedia</option>
                        <option value="Suspenso">Suspenso</option>
                        <option value="Animada">Animada</option>
                    </select>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary mt-2">Guardar</button>
    </form>
</div>